/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class apache_org_google_LoadSo */

#ifndef _Included_apache_org_google_LoadSo
#define _Included_apache_org_google_LoadSo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     apache_org_google_LoadSo
 * Method:    getName
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_apache_org_google_LoadSo_getName
  (JNIEnv *, jobject);

/*
 * Class:     apache_org_google_LoadSo
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_apache_org_google_LoadSo_stringFromJNI
  (JNIEnv *, jclass);

/*
 * Class:     apache_org_google_LoadSo
 * Method:    hello_form_c
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_apache_org_google_LoadSo_hello_1form_1c
  (JNIEnv *, jclass);

/*
 * Class:     apache_org_google_LoadSo
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_apache_org_google_LoadSo_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     apache_org_google_LoadSo
 * Method:    add_hello_InC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_apache_org_google_LoadSo_add_1hello_1InC
  (JNIEnv *, jclass, jstring);

/*
 * Class:     apache_org_google_LoadSo
 * Method:    add_intArray_InC
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_apache_org_google_LoadSo_add_1intArray_1InC
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     apache_org_google_LoadSo
 * Method:    calMethod1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_apache_org_google_LoadSo_calMethod1
  (JNIEnv *, jobject);

/*
 * Class:     apache_org_google_LoadSo
 * Method:    calMethod2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_apache_org_google_LoadSo_calMethod2
  (JNIEnv *, jobject);

/*
 * Class:     apache_org_google_LoadSo
 * Method:    calMethod3
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_apache_org_google_LoadSo_calMethod3
  (JNIEnv *, jobject);
JNIEXPORT void JNICALL Java_apache_org_google_LoadSo_calMethod4
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
